app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => 'web'], function () {
    Route::auth();

    Route::get('/', 'ItemController@index');

    Route::resource('item', 'ItemController');
    // Route::resource('history', 'HistoryController');
    Route::get('/history/{item}', 'HistoryController@index');

    Route::resource('purchase', 'PurchaseController');

    Route::resource('sale', 'SaleController');

    Route::get('/api/items', 'ItemController@get');
    Route::get('/api/items/{item}', 'ItemController@getById');
    Route::post('/api/items/create', 'ItemController@store');
    Route::put('/api/items/update/{item}', 'ItemController@update');
});

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    public static function get($search = null) {
        if ($search) {
            return self::where('code', 'like', "%$search%")->orwhere('name', 'like', "%$search%")->orderBy('code','asc')->paginate(15);
        } else {
            return self::orderBy('code','asc')->paginate(15);
        }
    }

    public function getCreateduserAttribute() {
        return \App\User::where('id',$this->created_by)->first();
    }

    public function getUpdateduserAttribute() {
        return \App\User::where('id',$this->updated_by)->first();
    }

    public function histories()
    {
        return $this->hasMany('App\History')->orderBy('created_at','desc');
    }
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Item;

class ItemController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $request->flash();
        return view('item.index', [
            'items' => Item::get($request->search)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'itemCode' => 'required',
            'itemName' => 'required|max:255',
            'itemQty' => 'required|numeric'
        ]);
        try {
            $item = new Item;
            $item->code = $request->itemCode;
            $item->name = $request->itemName;
            $item->qty = $item->stock = $request->itemQty;
            $item->created_by = $item->updated_by = $request->user()->id;
            $item->save();

            $history = new \App\History;
            $history->item_id = $item->id;
            $history->action = 'Dibuat Oleh ' . $item->Createduser->name;
            $history->save();
        } catch(\Exception $e){
            \DB::rollback();
        }


        return redirect('/item');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Item $item)
    {
        // return $item;
        $this->validate($request, [
            'itemCode' => 'required',
            'itemName' => 'required|max:255',
            'itemQty' => 'required|numeric'
        ]);
        try {
            if ($item->code != $request->itemCode) {
                $history = new \App\History;
                $history->item_id = $item->id;
                $history->action =
                    'Kode barang diubah dari ' . $item->code
                    . ' menjadi ' . $request->itemCode
                    . ' oleh ' . $request->user()->name;
                $history->save();

                $item->code = $request->itemCode;
            }

            if ($item->name != $request->itemName) {
                $history = new \App\History;
                $history->item_id = $item->id;
                $history->action =
                    'Nama barang diubah dari ' . $item->name
                    . ' menjadi ' . $request->itemName
                    . ' oleh ' . $request->user()->name;
                $history->save();

                $item->name = $request->itemName;
            }

            if ($item->stock != $request->itemQty) {
                $history = new \App\History;
                $history->item_id = $item->id;
                $history->action =
                    'Stock barang diubah dari ' . $item->stock
                    . ' menjadi ' . $request->itemQty
                    . ' oleh ' . $request->user()->name;
                $history->save();

                $item->stock = $request->itemQty;
            }

            $item->created_at = $item->created_at;
            $item->updated_by = $request->user()->id;
            $item->save();



        } catch(\Exception $e){
            \DB::rollback();
        }

        return redirect('/item');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Item $item)
    {
        $item->delete();
        return redirect('/item');
    }

    public function get(Request $request) {
        return Item::get($request->search);
    }

    public function getById(Item $item) {
        return $item;
    }
}

resources/views/item/index.blade.php
|@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <a href="#" class="btn add-new" role="button" data-toggle="modal" data-target="#formModal">
        <span class="glyphicon glyphicon-plus-sign"></span>
        Tambah Barang
    </a>
    <!--Start Item List-->
    <div class="panel panel-default">
        <div class="panel-heading padding-title">
            <div class="row">
                <div class="col-sm-5 col-xs-12">
                    <div style="margin-top: -5px;">
                        <h3><span class="glyphicon glyphicon-list"></span> Daftar Barang</h3>
                    </div>
                </div>
                <div class="col-sm-7 col-xs-12
                    <form class="navbar-form hidden-xs navbar-right form-inline" role="form" id="search-form-hidden-xs" name="search-form" action="{{ url('/item') }}">
                        <div class="form-group" style="margin-top:5px;">
                            <input type="text" class="form-control" placeholder="cari barang" id="searchItem" name="search" value="{{ old('search') }}"/>
                            <button type="submit" class="btn"><span class="glyphicon glyphicon-search"></span></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="panel-body" style="height: 100%; overflow: auto;">
            <!--Start Item Table-->
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Kode</th>
                        <th>Nama</th>
                        <th>Jlh</th>
                        <th>Dibuat Tgl</th>
                        <th>Diubah Tgl</th>
                    </tr>
                </thead>
                <tbody>
                     @foreach ($items as $item)
                        <tr>
                            <td>{{ $item->code }}</td>
                            <td>{{ $item->name }}</td>
                            <td>{{ $item->stock }}</td>
                            <td>{{ $item->created_at }} oleh <strong>{{ $item->createduser->name }}</strong></td>
                            <td>{{ $item->updated_at }} oleh <strong>{{ $item->updateduser->name }}</strong></td>
                            <td>
                                <a href="#" data-toggle="modal" data-target="#formModal" data-id="{{ $item->id }}">
                                    <span class="glyphicon glyphicon-edit"></span>
                                    Ubah
                                </a>
                                <a href="#" class="space" data-toggle="modal" data-target="#deleteModal" data-id="{{ $item->id }}">
                                    <span class="glyphicon glyphicon-remove-circle"></span>
                                    Hapus
                                </a>
                                <a href="{{ action('HistoryController@index', $item->id) }}" class="space">
                                    <span class="glyphicon glyphicon-time"></span>
                                    Riwayat
                                </a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            <!--End Item Table-->
            {!! $items->links() !!}
        </div>
    </div>
    <!--End Item List-->
</div>
<!--Start New Item-->
<div class="modal fade" role="dialog" id="formModal">
    <div class="modal-dialog">
        <!--Start Modal Content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" style="color: #ff0000;">&times;</button>
                <h4 class="modal-title">Detail Barang</h4>
            </div>
            <div class="modal-body">
                <form role="form" method="post" id="itemEditorial" name="frmItemEditorial" url="{{ url('/item') }}">
                    {!! csrf_field() !!}
                    {!! method_field('put') !!}
                    <div class="container-fluid" style="margin-left: 20px; margin-right: 20px;">
                        <div class="row" style="padding-bottom: 15px;">
                            <div class="col-xs-4" style="padding-right: 0px; width: auto;">
                                <label class="editorial-label">Kode Barang</label>
                            </div>
                            <div class="col-xs-1" style="padding-left: 8px; padding-right: 7px; width: auto;">
                                <label class="editorial-label">:</label>
                            </div>
                            <div class="col-xs-7" style="padding-left: 0px; width: 414px;">
                                <input class="form-control" id="itemCode" name="itemCode" type="text" placeholder="kode barang">
                            </div>
                        </div>
                        <div class="row" style="padding-bottom: 15px;">
                            <div class="col-xs-4" style="padding-right: 0px; width: auto;">
                                <label class="editorial-label">Nama Barang</label>
                            </div>
                            <div class="col-xs-1" style="padding-left: 5px; padding-right: 7px; width: auto;">
                                <label class="editorial-label">:</label>
                            </div>
                            <div class="col-xs-7" style="padding-left: 0px; width: 414px;">
                                <input class="form-control" id="itemName" name="itemName" type="text" placeholder="nama barang">
                            </div>
                        </div>
                        <div class="row" style="padding-bottom: 15px;">
                            <div class="col-xs-4" style="padding-right: 0px; width: auto;">
                                <label class="editorial-label">Jlh Barang</label>
                            </div>
                            <div class="col-xs-1" style="padding-left: 20px; padding-right: 7px; width: auto;">
                                <label class="editorial-label">:</label>
                            </div>
                            <div class="col-xs-7" style="padding-left: 0px; width: 414px;">
                                <input class="form-control" id="itemQty" name="itemQty" type="number" placeholder="0">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-default" style="background-color: #0066ff; color: #fff;">
                        Simpan
                    </button>
                    <button type="button" class="btn btn-default" data-dismiss="modal" style="background-color: #ff0000; color: #fff;">
                        Tutup
                    </button>
                </div>
            </form>
        </div>
        <!--End Modal Content-->
    </div>
</div>
<!--End New Item-->
<div class="modal fade" tabindex="-1" role="dialog" id="deleteModal">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Hapus Barang?</h4>
      </div>
      <div class="modal-footer">
        <form method="post">
            {!! csrf_field() !!}
            {!! method_field('delete') !!}
            <input class="btn btn-danger" type="submit" value="Hapus">
            <input class="btn btn-default" type="button" value="Batal" data-dismiss="modal">
        </form>
      </div>
    </div>
  </div>
</div>


@endsection
@section('script')
<script>
    $('#formModal').on('show.bs.modal', function (event) {
        var id = $(event.relatedTarget).data('id');
        var form = $(this).find('form')[0];
        if (id) {
            $.getJSON( '/api/items/' + id, function( item ) {
                console.log( "success" );
                $('#itemCode').val(item.code);
                $('#itemName').val(item.name);
                $('#itemQty').val(item.stock);
            });
            $('#formModal input[name="_method"]').val('put');
            form.action = '/api/items/update/' + id;
        } else {
            $('#itemCode').val('');
            $('#itemName').val('');
            $('#itemQty').val('');
            $('#formModal input[name="_method"]').val('post');
            form.action = 'api/items/create';
        }
    });
    $('#deleteModal').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget);
        var id = button.data('id');
        var modal = $(this);
        modal.find('form')[0].action = '/item/' + id;
    });
</script>
@endsection